import { SceneManager } from "../../src/sceneManager";

/** Extract the id from a SceneManager add*() result */
function getId(result: string | { id: string }): string {
    if (typeof result === "string") {
        throw new Error(`Expected { id }, got error: ${result}`);
    }
    return result.id;
}

/**
 * Tests for the snippet export feature — partial code generation
 * for adding features to an existing Babylon.js scene.
 */
describe("Scene MCP Server – Snippet Export", () => {
    let mgr: SceneManager;

    beforeEach(() => {
        mgr = new SceneManager();
        // Build a rich scene to extract snippets from
        mgr.createScene("TestScene");

        // Lights
        mgr.addLight("TestScene", "sunLight", "DirectionalLight", {
            direction: [0.5, -1, 0.5],
            intensity: 0.8,
            shadowEnabled: true,
            shadowMapSize: 2048,
        });
        mgr.addLight("TestScene", "ambientLight", "HemisphericLight", {
            direction: [0, 1, 0],
            intensity: 0.3,
        });

        // Materials
        const groundMatId = getId(
            mgr.addMaterial("TestScene", "groundMat", "StandardMaterial", {
                diffuseColor: [0.4, 0.6, 0.4],
            })
        );
        const boxMatId = getId(
            mgr.addMaterial("TestScene", "boxMat", "PBRMaterial", {
                metallic: 0.8,
                roughness: 0.2,
            })
        );

        // Meshes
        const groundId = getId(mgr.addMesh("TestScene", "ground", "Ground", { width: 20, height: 20 }, { position: { x: 0, y: 0, z: 0 } }));
        mgr.setMeshProperties("TestScene", groundId, { materialId: groundMatId, receiveShadows: true });

        const box1Id = getId(mgr.addMesh("TestScene", "box1", "Box", { size: 2 }, { position: { x: 0, y: 1, z: 0 } }));
        mgr.setMeshProperties("TestScene", box1Id, { materialId: boxMatId, castsShadows: true });

        getId(mgr.addMesh("TestScene", "sphere1", "Sphere", { diameter: 1.5 }, { position: { x: 3, y: 0.75, z: 0 } }));
        mgr.setMeshProperties("TestScene", "sphere1", { castsShadows: true });

        // Physics
        mgr.addPhysicsBody("TestScene", "box1", 2, "Box");
        mgr.addPhysicsBody("TestScene", "ground", 0, "Box");

        // Animation
        mgr.addAnimation("TestScene", "rotateBox", box1Id, "rotation.y", 30, [
            { frame: 0, value: 0 },
            { frame: 60, value: Math.PI * 2 },
        ]);

        // Particle system
        mgr.addParticleSystem("TestScene", "sparks", 500, "box1", {
            minLifeTime: 0.3,
            maxLifeTime: 1.0,
        });

        // Render pipeline
        mgr.configureRenderPipeline("TestScene", {
            bloomEnabled: true,
            bloomThreshold: 0.8,
            fxaaEnabled: true,
        });

        // Glow layer
        mgr.addGlowLayer("TestScene", "mainGlow", { intensity: 0.5 });

        // Camera (for completeness)
        mgr.addCamera("TestScene", "mainCam", "ArcRotateCamera", {
            alpha: -Math.PI / 2,
            beta: Math.PI / 3,
            radius: 10,
            target: [0, 1, 0],
        });
    });

    // ── Basic functionality ───────────────────────────────────────────────

    it("returns null for nonexistent scene", () => {
        expect(mgr.exportSnippet("noSuchScene", { categories: ["shadows"] })).toBeNull();
    });

    it("generates non-empty code for a valid category", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["shadows"] });
        expect(snippet).toBeTruthy();
        expect(snippet!.length).toBeGreaterThan(0);
    });

    // ── Header / preamble ─────────────────────────────────────────────────

    it("includes the preamble comment with snippet header", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["shadows"] })!;
        expect(snippet).toContain("Code snippet generated by Scene MCP Server");
        expect(snippet).toContain("Add this code to your existing Babylon.js scene");
    });

    it("lists assumed variables in the preamble", () => {
        // Shadows category: creates the light, but references existing meshes for shadow casters
        const snippet = mgr.exportSnippet("TestScene", { categories: ["shadows"] })!;
        expect(snippet).toContain("assumes the following variables already exist");
        expect(snippet).toContain("scene");
    });

    it("uses custom sceneVarName in assumed variables", () => {
        const snippet = mgr.exportSnippet("TestScene", {
            categories: ["shadows"],
            sceneVarName: "myScene",
        })!;
        expect(snippet).toContain("myScene");
    });

    // ── Shadows category ──────────────────────────────────────────────────

    it("shadows category generates ShadowGenerator code", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["shadows"] })!;
        expect(snippet).toContain("ShadowGenerator");
        expect(snippet).toContain("Shadow Setup");
    });

    it("shadows category includes shadow caster assignments", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["shadows"] })!;
        expect(snippet).toContain("addShadowCaster");
    });

    it("shadows category includes receiveShadows", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["shadows"] })!;
        expect(snippet).toContain("receiveShadows = true");
    });

    it("shadows category generates the shadow-enabled light", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["shadows"] })!;
        expect(snippet).toContain("DirectionalLight");
        expect(snippet).toContain("sunLight");
    });

    it("shadows category does NOT include non-shadow lights", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["shadows"] })!;
        expect(snippet).not.toContain("HemisphericLight");
        expect(snippet).not.toContain("ambientLight");
    });

    // ── Physics category ──────────────────────────────────────────────────

    it("physics category generates physics init code", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["physics"] })!;
        expect(snippet).toContain("HavokPhysics");
        expect(snippet).toContain("HavokPlugin");
    });

    it("physics category includes physics body code", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["physics"] })!;
        expect(snippet).toContain("PhysicsBody");
        expect(snippet).toContain("PhysicsShape");
    });

    it("physics category creates meshes that have physics", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["physics"] })!;
        expect(snippet).toContain("box1");
        expect(snippet).toContain("ground");
    });

    // ── Animations category ───────────────────────────────────────────────

    it("animations category generates animation creation code", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["animations"] })!;
        expect(snippet).toContain("Animation");
        expect(snippet).toContain("rotateBox");
    });

    it("animations category attaches animation to target", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["animations"] })!;
        expect(snippet).toContain("animations.push");
    });

    // ── Particles category ────────────────────────────────────────────────

    it("particles category generates particle system code", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["particles"] })!;
        expect(snippet).toContain("ParticleSystem");
        expect(snippet).toContain("sparks");
    });

    // ── Post-processing category ──────────────────────────────────────────

    it("postProcessing category generates render pipeline code", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["postProcessing"] })!;
        expect(snippet).toContain("DefaultRenderingPipeline");
        expect(snippet).toContain("bloomEnabled");
        expect(snippet).toContain("fxaaEnabled");
    });

    // ── Glow category ─────────────────────────────────────────────────────

    it("glow category generates glow layer code", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["glow"] })!;
        expect(snippet).toContain("GlowLayer");
        expect(snippet).toContain("mainGlow");
    });

    // ── Materials category ────────────────────────────────────────────────

    it("materials category generates all materials", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["materials"] })!;
        expect(snippet).toContain("StandardMaterial");
        expect(snippet).toContain("groundMat");
        expect(snippet).toContain("PBRMaterial");
        expect(snippet).toContain("boxMat");
    });

    // ── Lights category ───────────────────────────────────────────────────

    it("lights category generates all lights", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["lights"] })!;
        expect(snippet).toContain("DirectionalLight");
        expect(snippet).toContain("HemisphericLight");
    });

    // ── Meshes category ───────────────────────────────────────────────────

    it("meshes category generates all meshes", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["meshes"] })!;
        expect(snippet).toContain("CreateGround");
        expect(snippet).toContain("CreateBox");
        expect(snippet).toContain("CreateSphere");
    });

    // ── Object ID selection ───────────────────────────────────────────────

    it("objectIds selects specific objects by ID", () => {
        const boxId = mgr.getScene("TestScene")!.meshes.find((m) => m.name === "box1")!.id;
        const snippet = mgr.exportSnippet("TestScene", { objectIds: [boxId] })!;
        expect(snippet).toContain("box1");
        expect(snippet).toContain("CreateBox");
        // Should NOT *create* unrelated objects (they may appear as assumed variables)
        expect(snippet).not.toContain("CreateSphere");
        expect(snippet).not.toContain("new BABYLON.DirectionalLight");
    });

    it("objectIds selects objects by name", () => {
        const snippet = mgr.exportSnippet("TestScene", { objectIds: ["sunLight"] })!;
        expect(snippet).toContain("DirectionalLight");
        expect(snippet).toContain("sunLight");
    });

    it("objectIds + categories can be combined", () => {
        const snippet = mgr.exportSnippet("TestScene", {
            objectIds: ["box1"],
            categories: ["postProcessing"],
        })!;
        // Should have the box
        expect(snippet).toContain("CreateBox");
        // And the render pipeline
        expect(snippet).toContain("DefaultRenderingPipeline");
    });

    // ── Multiple categories ───────────────────────────────────────────────

    it("multiple categories combine correctly", () => {
        const snippet = mgr.exportSnippet("TestScene", {
            categories: ["shadows", "particles", "glow"],
        })!;
        expect(snippet).toContain("ShadowGenerator");
        expect(snippet).toContain("ParticleSystem");
        expect(snippet).toContain("GlowLayer");
    });

    // ── Format: UMD vs ES6 ────────────────────────────────────────────────

    it("UMD format uses BABYLON.* prefix", () => {
        const snippet = mgr.exportSnippet("TestScene", {
            categories: ["materials"],
            format: "umd",
        })!;
        expect(snippet).toContain("BABYLON.StandardMaterial");
    });

    it("ES6 format uses import statements", () => {
        const snippet = mgr.exportSnippet("TestScene", {
            categories: ["materials"],
            format: "es6",
        })!;
        expect(snippet).toContain("import {");
        expect(snippet).toContain("@babylonjs/core");
        // Should NOT have BABYLON.* prefix
        expect(snippet).not.toContain("BABYLON.StandardMaterial");
    });

    // ── Does NOT include scene/engine boilerplate ─────────────────────────

    it("does NOT include engine or canvas creation", () => {
        const snippet = mgr.exportSnippet("TestScene", {
            categories: ["shadows", "physics", "animations", "particles", "postProcessing"],
        })!;
        expect(snippet).not.toContain("new BABYLON.Engine");
        expect(snippet).not.toContain('getElementById("renderCanvas")');
        expect(snippet).not.toContain("new BABYLON.Scene");
        expect(snippet).not.toContain("runRenderLoop");
    });

    it("does NOT include HTML boilerplate", () => {
        const snippet = mgr.exportSnippet("TestScene", { categories: ["shadows"] })!;
        expect(snippet).not.toContain("<!DOCTYPE");
        expect(snippet).not.toContain("<html>");
        expect(snippet).not.toContain("<script");
    });

    // ── Assumed variables tracking ────────────────────────────────────────

    it("tracks assumed variables for cross-references", () => {
        // Animation snippet references box1 as a target but doesn't create it
        const snippet = mgr.exportSnippet("TestScene", { categories: ["animations"] })!;
        expect(snippet).toContain("assumes the following variables already exist");
        expect(snippet).toContain("box1");
    });

    it("does not list created variables as assumed", () => {
        // When we include meshes category, box1 is created, not assumed
        const snippet = mgr.exportSnippet("TestScene", {
            categories: ["meshes", "animations"],
        })!;
        // box1 should appear in code (it's created), but not in the "assumed" list
        const preambleEnd = snippet.indexOf("═══", snippet.indexOf("═══") + 3);
        // box1 is created, so it should appear only in code, not in the assumed section
        // (The assumed section only contains variables NOT created by the snippet)
        const bodySection = snippet.slice(preambleEnd);
        expect(bodySection).toContain("box1");
    });

    // ── Edge cases ────────────────────────────────────────────────────────

    it("empty scene returns minimal snippet", () => {
        mgr.createScene("EmptyScene");
        const snippet = mgr.exportSnippet("EmptyScene", { categories: ["shadows"] })!;
        expect(snippet).toContain("Code snippet generated by Scene MCP Server");
        // No shadow code since there are no shadow-enabled lights
        expect(snippet).not.toContain("ShadowGenerator");
    });

    it("category with no matching items returns just the header", () => {
        mgr.createScene("NoSounds");
        const snippet = mgr.exportSnippet("NoSounds", { categories: ["sounds"] })!;
        expect(snippet).toContain("Code snippet generated by Scene MCP Server");
        // No sound code
        expect(snippet).not.toContain("StaticSound");
    });
});
