/**
 * FullFeatured
 * A complex scene demonstrating multiple features
 *
 * Generated by Babylon.js Scene MCP Server
 * Version: 1.0.0
 */

import { Animation, ArcRotateCamera, Color3, Color4, CreateSoundAsync, DefaultRenderingPipeline, DirectionalLight, Engine, GlowLayer, HavokPlugin, HemisphericLight, HighlightLayer, MeshBuilder, PBRMaterial, PhysicsBody, PhysicsMotionType, PhysicsShapeBox, Scene, StandardMaterial, Vector3 } from "@babylonjs/core";
import HavokPhysics from "@babylonjs/havok";
import "@babylonjs/core/Audio/v2";



async function createScene() {
    const canvas = document.getElementById("renderCanvas") ;
    const engine = new Engine(canvas, true, { stencil: true });

    const scene = new Scene(engine);

    // ─── Environment ──────────────────────────────────────────────────────────
    scene.clearColor = new Color4(0.05, 0.05, 0.1, 1);
    scene.ambientColor = new Color3(0.1, 0.1, 0.15);
    scene.fogEnabled = true;
    scene.fogMode = Scene.FOGMODE_LINEAR;
    scene.fogColor = new Color3(0.05, 0.05, 0.1);
    scene.fogDensity = 0.01;
    scene.gravity = new Vector3(0, -9.81, 0);

    // ─── Physics ──────────────────────────────────────────────────────────────
    const havokInstance = await HavokPhysics();
    const havokPlugin = new HavokPlugin(true, havokInstance);
    scene.enablePhysics(new Vector3(0, -9.81, 0), havokPlugin);

    // ─── Cameras ──────────────────────────────────────────────────────────────
    const mainCam = new ArcRotateCamera("mainCam", 1.57, 1.2, 15, new Vector3(0, 1, 0), scene);
    mainCam.uniqueId = 1;
    mainCam.attachControl(canvas, true);

    scene.activeCamera = mainCam;

    // ─── Lights ───────────────────────────────────────────────────────────────
    const ambient = new HemisphericLight("ambient", new Vector3(0, 1, 0), scene);
    ambient.uniqueId = 1;
    ambient.intensity = 0.3;

    const sun = new DirectionalLight("sun", new Vector3(0, -1, 0), scene);
    sun.uniqueId = 2;
    sun.intensity = 0.7;

    // ─── Materials ────────────────────────────────────────────────────────────
    const floorMat = new PBRMaterial("floorMat", scene);
    floorMat.uniqueId = 1;
    floorMat.albedoColor = new Color3(0.3, 0.3, 0.35);
    floorMat.metallic = 0.1;
    floorMat.roughness = 0.9;

    const glowMat = new StandardMaterial("glowMat", scene);
    glowMat.uniqueId = 2;
    glowMat.emissiveColor = new Color3(0, 0.5, 1);

    // ─── Meshes ───────────────────────────────────────────────────────────────
    const floor = MeshBuilder.CreateGround("floor", { width: 20, height: 20 }, scene);
    floor.uniqueId = 1;
    floor.receiveShadows = true;

    const glowSphere = MeshBuilder.CreateSphere("glowSphere", { diameter: 1.5 }, scene);
    glowSphere.uniqueId = 2;
    glowSphere.position = new Vector3(0, 2, 0);
    glowSphere.receiveShadows = true;

    const hlBox = MeshBuilder.CreateBox("hlBox", { size: 1 }, scene);
    hlBox.uniqueId = 3;
    hlBox.position = new Vector3(-3, 0.5, 0);
    hlBox.receiveShadows = true;

    // ─── Material Assignments ─────────────────────────────────────────────────
    floor.material = floorMat;
    glowSphere.material = glowMat;

    // ─── Animations ───────────────────────────────────────────────────────────
    const float = new Animation("float", "position.y", 60, Animation.ANIMATIONTYPE_FLOAT, Animation.ANIMATIONLOOPMODE_CYCLE);
    float.setKeys([
        { frame: 0, value: 2 },
        { frame: 30, value: 3 },
        { frame: 60, value: 2 },
    ]);

    // Attach animations to targets
    glowSphere.animations.push(float);

    // ─── Physics Bodies ───────────────────────────────────────────────────────
    // Physics for floor
    const floorPhysicsBody = new PhysicsBody(floor, PhysicsMotionType.STATIC, false, floor.getScene());
    const floorPhysicsShape = PhysicsShapeBox.FromMesh(floor);
    floorPhysicsBody.setMassProperties({ mass: 0 });
    floorPhysicsBody.shape = floorPhysicsShape;

    // ─── Sounds (Audio V2) ────────────────────────────────────────────────────
    // Sound: ambient
    const ambient = await CreateSoundAsync("ambient", "sounds/ambient.mp3", scene.audioEngine!, {
        autoplay: true,
        loop: true,
        volume: 0.5,
    });

    // ─── Render Pipeline (Post-Processing) ────────────────────────────────────
    const defaultPipeline = new DefaultRenderingPipeline("defaultPipeline", true, scene, [scene.activeCamera!]);
    defaultPipeline.bloomEnabled = true;
    defaultPipeline.bloomKernel = 64;
    defaultPipeline.bloomWeight = 0.3;
    defaultPipeline.bloomThreshold = 0.8;
    defaultPipeline.fxaaEnabled = true;

    // ─── Glow Layers ──────────────────────────────────────────────────────────
    // Glow Layer: mainGlow
    const mainGlow = new GlowLayer("mainGlow", scene);
    mainGlow.intensity = 0.5;
    mainGlow.addIncludedOnlyMesh(glowSphere);

    // ─── Highlight Layers ─────────────────────────────────────────────────────
    // Highlight Layer: selection
    const selection = new HighlightLayer("selection", scene);
    selection.addMesh(hlBox, new Color3(1, 1, 0));

    // ─── Render Loop ──────────────────────────────────────────────────────────
    engine.runRenderLoop(() => {
        scene.render();
    });

    window.addEventListener("resize", () => {
        engine.resize();
    });
}

createScene().catch(function(e) { console.error("Scene init error:", e); });