/**
 * AnimatedScene
 * A scene with multiple animations and animation groups
 *
 * Generated by Babylon.js Scene MCP Server
 * Version: 1.0.0
 */

import { Animation, AnimationGroup, ArcRotateCamera, Color3, Color4, DirectionalLight, Engine, MeshBuilder, Scene, Vector3 } from "@babylonjs/core";



async function createScene() {
    const canvas = document.getElementById("renderCanvas") ;
    const engine = new Engine(canvas, true, { stencil: true });

    const scene = new Scene(engine);

    // ─── Environment ──────────────────────────────────────────────────────────
    scene.clearColor = new Color4(0.2, 0.2, 0.3, 1);
    scene.ambientColor = new Color3(0, 0, 0);
    scene.gravity = new Vector3(0, -9.81, 0);

    // ─── Cameras ──────────────────────────────────────────────────────────────
    const cam = new ArcRotateCamera("cam", -1.5707963267948966, 1.5707963267948966, 10, Vector3.Zero(), scene);
    cam.uniqueId = 1;
    cam.attachControl(canvas, true);

    scene.activeCamera = cam;

    // ─── Lights ───────────────────────────────────────────────────────────────
    const light = new DirectionalLight("light", new Vector3(0, -1, 0), scene);
    light.uniqueId = 1;

    // ─── Meshes ───────────────────────────────────────────────────────────────
    const sphere = MeshBuilder.CreateSphere("sphere", { diameter: 2 }, scene);
    sphere.uniqueId = 1;
    sphere.receiveShadows = true;

    const pulsingBox = MeshBuilder.CreateBox("pulsingBox", { size: 1 }, scene);
    pulsingBox.uniqueId = 2;
    pulsingBox.position = new Vector3(3, 0, 0);
    pulsingBox.receiveShadows = true;

    // ─── Animations ───────────────────────────────────────────────────────────
    const bounce = new Animation("bounce", "position.y", 60, Animation.ANIMATIONTYPE_FLOAT, Animation.ANIMATIONLOOPMODE_CYCLE);
    bounce.setKeys([
        { frame: 0, value: 0 },
        { frame: 30, value: 3 },
        { frame: 60, value: 0 },
    ]);

    const spin = new Animation("spin", "rotation.y", 60, Animation.ANIMATIONTYPE_FLOAT, Animation.ANIMATIONLOOPMODE_CYCLE);
    spin.setKeys([
        { frame: 0, value: 0 },
        { frame: 60, value: 6.28 },
    ]);

    const pulse = new Animation("pulse", "scaling", 60, Animation.ANIMATIONTYPE_VECTOR3, Animation.ANIMATIONLOOPMODE_CYCLE);
    pulse.setKeys([
        { frame: 0, value: new Vector3(1, 1, 1) },
        { frame: 30, value: new Vector3(1.5, 1.5, 1.5) },
        { frame: 60, value: new Vector3(1, 1, 1) },
    ]);

    // Attach animations to targets
    sphere.animations.push(bounce);
    sphere.animations.push(spin);
    pulsingBox.animations.push(pulse);

    // ─── Animation Groups ─────────────────────────────────────────────────────
    const sphereMotion = new AnimationGroup("sphereMotion", scene);
    sphereMotion.addTargetedAnimation(bounce, sphere);
    sphereMotion.addTargetedAnimation(spin, sphere);
    sphereMotion.loopAnimation = true;

    // ─── Render Loop ──────────────────────────────────────────────────────────
    engine.runRenderLoop(() => {
        scene.render();
    });

    window.addEventListener("resize", () => {
        engine.resize();
    });
}

createScene().catch(function(e) { console.error("Scene init error:", e); });