/**
 * PhysicsPlayground
 * A physics-enabled scene with dynamic bodies and constraints
 *
 * Generated by Babylon.js Scene MCP Server
 * Version: 1.0.0
 */

import {
    ArcRotateCamera,
    Color3,
    Color4,
    Engine,
    HavokPlugin,
    HemisphericLight,
    MeshBuilder,
    Physics6DoFConstraint,
    PhysicsBody,
    PhysicsConstraintAxis,
    PhysicsMotionType,
    PhysicsShapeBox,
    PhysicsShapeSphere,
    Scene,
    Vector3,
} from "@babylonjs/core";
import HavokPhysics from "@babylonjs/havok";

// eslint-disable-next-line @typescript-eslint/naming-convention
async function createScene() {
    const canvas = document.querySelector<HTMLCanvasElement>("#renderCanvas");
    if (!canvas) {
        throw new Error("Canvas element '#renderCanvas' not found");
    }
    const engine = new Engine(canvas, true, { stencil: true });

    const scene = new Scene(engine);

    // ─── Environment ──────────────────────────────────────────────────────────
    scene.clearColor = new Color4(0.2, 0.2, 0.3, 1);
    scene.ambientColor = new Color3(0, 0, 0);
    scene.gravity = new Vector3(0, -9.81, 0);

    // ─── Physics ──────────────────────────────────────────────────────────────
    const havokInstance = await HavokPhysics();
    const havokPlugin = new HavokPlugin(true, havokInstance);
    scene.enablePhysics(new Vector3(0, -9.81, 0), havokPlugin);

    // ─── Cameras ──────────────────────────────────────────────────────────────
    const cam = new ArcRotateCamera("cam", -1.5707963267948966, 1.5707963267948966, 10, Vector3.Zero(), scene);
    cam.uniqueId = 1;
    cam.attachControl(canvas, true);

    scene.activeCamera = cam;

    // ─── Lights ───────────────────────────────────────────────────────────────
    const light = new HemisphericLight("light", new Vector3(0, 1, 0), scene);
    light.uniqueId = 1;

    // ─── Meshes ───────────────────────────────────────────────────────────────
    const ground = MeshBuilder.CreateGround("ground", { width: 20, height: 20 }, scene);
    ground.uniqueId = 1;
    ground.receiveShadows = true;

    const box1 = MeshBuilder.CreateBox("box1", { size: 1 }, scene);
    box1.uniqueId = 2;
    box1.position = new Vector3(0, 5, 0);
    box1.receiveShadows = true;

    const sphere1 = MeshBuilder.CreateSphere("sphere1", { diameter: 1 }, scene);
    sphere1.uniqueId = 3;
    sphere1.position = new Vector3(2, 8, 0);
    sphere1.receiveShadows = true;

    // ─── Physics Bodies ───────────────────────────────────────────────────────
    // Physics for ground
    const groundPhysicsBody = new PhysicsBody(ground, PhysicsMotionType.STATIC, false, ground.getScene());
    const groundPhysicsShape = PhysicsShapeBox.FromMesh(ground);
    groundPhysicsBody.setMassProperties({ mass: 0 });
    groundPhysicsBody.shape = groundPhysicsShape;

    // Physics for box1
    const box1PhysicsBody = new PhysicsBody(box1, PhysicsMotionType.DYNAMIC, false, box1.getScene());
    const box1PhysicsShape = PhysicsShapeBox.FromMesh(box1);
    box1PhysicsBody.setMassProperties({ mass: 1 });
    box1PhysicsShape.material = { restitution: 0.5 };
    box1PhysicsBody.shape = box1PhysicsShape;

    // Physics for sphere1
    const sphere1PhysicsBody = new PhysicsBody(sphere1, PhysicsMotionType.DYNAMIC, false, sphere1.getScene());
    const sphere1PhysicsShape = PhysicsShapeSphere.FromMesh(sphere1);
    sphere1PhysicsBody.setMassProperties({ mass: 2 });
    sphere1PhysicsShape.material = { restitution: 0.7 };
    sphere1PhysicsBody.shape = sphere1PhysicsShape;

    // ─── Physics Constraints ──────────────────────────────────────────────────
    // Physics Constraint: hinge1 (Hinge)
    const hinge1 = new Physics6DoFConstraint(
        {
            pivotA: new Vector3(0.5, 0, 0),
            pivotB: new Vector3(-0.5, 0, 0),
            axisA: new Vector3(0, 1, 0),
            axisB: new Vector3(0, 1, 0),
        },
        [
            { axis: PhysicsConstraintAxis.LINEAR_X, minLimit: 0, maxLimit: 0 },
            { axis: PhysicsConstraintAxis.LINEAR_Y, minLimit: 0, maxLimit: 0 },
            { axis: PhysicsConstraintAxis.LINEAR_Z, minLimit: 0, maxLimit: 0 },
            { axis: PhysicsConstraintAxis.ANGULAR_Y, minLimit: 0, maxLimit: 0 },
            { axis: PhysicsConstraintAxis.ANGULAR_Z, minLimit: 0, maxLimit: 0 },
        ],
        scene
    );
    box1PhysicsBody.addConstraint(sphere1PhysicsBody, hinge1);

    // ─── Render Loop ──────────────────────────────────────────────────────────
    engine.runRenderLoop(() => {
        scene.render();
    });

    window.addEventListener("resize", () => {
        engine.resize();
    });
}

// eslint-disable-next-line github/no-then
createScene().catch(function (e) {
    // eslint-disable-next-line no-console
    console.error("Scene init error:", e);
});
